version: '2.1'

services:
    db:
        build: ./db_stuff
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        healthcheck:
            test: "exit 0"
    
    app:
        build: .
        depends_on:
            db:
                condition: service_healthy
        entrypoint:
            - /usr/local/bin/docker-entrypoint.sh
        ports:
            - "3000"
    redis:
        image: redis
        ports:
            - "6379"